package explainer //nolint golint

// SessionDescription is generated by a WebRTC Agent. This is used to transport
// Offers and Answers.
type SessionDescription struct {
	Type string `json:"type"`
	SDP  string `json:"sdp"`
}
