// SPDX-FileCopyrightText: 2023 The Pion community <https://pion.ly>
// SPDX-License-Identifier: MIT

// Code generated by "json-ice --type=Message"; DO NOT EDIT.

package output

import "github.com/moznion/go-json-ice/serializer"

func MarshalMessageAsJSON(s *Message) ([]byte, error) {
	buff := make([]byte, 1, 80)
	buff[0] = '{'
	buff = append(buff, "\"message\":"...)
	buff = serializer.AppendSerializedString(buff, s.Message)
	buff = append(buff, ',')
	if s.Sources == nil {
		buff = append(buff, "\"source\":null,"...)
	} else {
		buff = append(buff, "\"source\":"...)
		buff = append(buff, '[')
		for _, v := range s.Sources {
			if marshaled, err := v.MarshalJSON(); err != nil {
				return nil, err
			} else {
				buff = append(buff, marshaled...)
			}

			buff = append(buff, ',')
		}
		if buff[len(buff)-1] == ',' {
			buff[len(buff)-1] = ']'
		} else {
			buff = append(buff, ']')
		}

		buff = append(buff, ',')
	}
	if buff[len(buff)-1] == ',' {
		buff[len(buff)-1] = '}'
	} else {
		buff = append(buff, '}')
	}
	return buff, nil
}
