// SPDX-FileCopyrightText: 2023 The Pion community <https://pion.ly>
// SPDX-License-Identifier: MIT

// Code generated by "json-ice --type=Source"; DO NOT EDIT.

package output

import "github.com/moznion/go-json-ice/serializer"

func MarshalSourceAsJSON(s *Source) ([]byte, error) {
	buff := make([]byte, 1, 54)
	buff[0] = '{'
	buff = append(buff, "\"type\":"...)
	if marshaled, err := s.Type.MarshalJSON(); err != nil {
		return nil, err
	} else {
		buff = append(buff, marshaled...)
	}

	buff = append(buff, ',')
	buff = append(buff, "\"line\":"...)
	buff = serializer.AppendSerializedInt(buff, int64(s.Line))
	buff = append(buff, ',')
	if buff[len(buff)-1] == ',' {
		buff[len(buff)-1] = '}'
	} else {
		buff = append(buff, '}')
	}
	return buff, nil
}
